"""migration

Revision ID: fb0ba2577363
Revises: 
Create Date: 2025-06-09 23:39:16.329818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0ba2577363'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('min_gpa', sa.Float(), nullable=True),
    sa.Column('min_ielts', sa.Float(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('scholarship_institution', sa.String(length=200), nullable=True),
    sa.Column('scholarship_coverage', sa.String(length=100), nullable=True),
    sa.Column('eligible_regions_nationalities', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_level', sa.String(length=50), nullable=True),
    sa.Column('preferred_country', sa.String(length=100), nullable=True),
    sa.Column('ielts_score', sa.Float(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('field_of_study', sa.String(length=100), nullable=True),
    sa.Column('sop_quality', sa.String(length=50), nullable=True),
    sa.Column('research_experience', sa.Float(), nullable=True),
    sa.Column('extracurricular_score', sa.Float(), nullable=True),
    sa.Column('need', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('users')
    op.drop_table('scholarships')
    # ### end Alembic commands ###
